---
- name: capture hosts for all compliance policies
  hosts: all
  gather_facts: no
  tasks:

    - name: create standard policy host list
      template:
        src: templates/STD_host_file_template.j2
        dest: /home/runner/files/std_compliance_hosts
      delegate_to: localhost


    - name: create hipaa policy host list
      template:
        src: templates/HIPAA_host_file_template.j2
        dest: /home/runner/files/hipaa_compliance_hosts
      delegate_to: localhost


    - ansible.builtin.debug:
      msg: "the value of standard is {{lookup('ansible.builtin.file', '/home/runner/files/std_compliance_hosts') }}"


    - ansible.builtin.debug:
      msg: "the value of hippa is {{lookup('ansible.builtin.file', '/home/runner/files/hipaa_compliance_hosts') }}"



