---
- name: capture hosts for all compliance policies
  hosts: all
  gather_facts: no
  vars_files:
    - secrets_folder/tokens.yml
  tasks:

    - name: create standard policy host list
      template:
        src: templates/STD_host_file_template.j2
        dest: /tmp/std_compliance_hosts
      delegate_to: localhost


    - name: create hipaa policy host list
      template:
        src: templates/HIPAA_host_file_template.j2
        dest: /tmp/hipaa_compliance_hosts
      delegate_to: localhost


    - name: standard hosts
      ansible.builtin.debug:
        msg: "the value of standard is {{lookup('ansible.builtin.file', '/tmp/std_compliance_hosts') }}"


    - ansible.builtin.debug:
        msg: "the value of hippa is {{lookup('ansible.builtin.file', '/tmp/hipaa_compliance_hosts') }}"


    - ansible.builtin.debug:
        msg: "{{ offline_token }}"
